### PR TITLE
Add support for Django 1.9 and replace StringIO with BytesIO

### PR DESCRIPTION
**Pull request by Azelphur**
This is the same patch as #50 but with a try except wrapped around the import at the top, which I believe addresses the issue with accepting this patch?

Hopefully this gets things working in Django 1.9, at first glance it seems to work.

### CODE REVIEW

**Comment by nikksbagul** [comment]
After creation of topic get this issue
`can't adapt type 'dict'`
But topic created successfully how to resolved this issue.

**Comment by slav0nic** [comment]
python, django version?

**Comment by Azelphur** [comment]
Can you also provide a complete traceback?

**Comment by nikksbagul** [comment]
I have setup Django 1.9.1 together with python 3.4.
When I calling `update_read(request.user)` method of Topic model then this issue is occurred.

**Comment by slav0nic** [comment]
are you use latest version? looks like it was fixed in the latest commits

**Pull request merged**
